server:
  port: 8000
spring:
  application:
    name: gulimall-member
  profiles:
    active: dev
mybatis-plus:
  #id自增
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

