server:
  port: 7000
spring:
#  application:
#    name: gulimall-coupon
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_sms?serverTimezone=GMT%2b8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.183:8848
      config:
        serverAddr: 192.168.31.183:8848
        namespace: gulimall-coupon
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  redis:
    host: 192.168.31.183
mybatis-plus:
  #id自增
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
#coupon:
#  user:
#    name: localname
#    age: 19