server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.183:8848
  redis:
    host: 192.168.31.183
  thymeleaf:
    cache: false
  session:
    store-type: redis
