server:
  port: 11000
spring:
  application:
    name: gulimall-ware
  datasource:
    username: root
    password: root
#    url: jdbc:mysql://localhost:3306/gulimall_wms?serverTimezone=GMT%2b8
    url: jdbc:mysql://localhost:3306/gulimall_wms?serverTimezone=GMT%2b8&&useInformationSchema=false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.183:8848
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.31.183
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  #id自增
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

